% Create a biquad antenna
% Generated by MATLAB(R) 9.6 and Antenna Toolbox 4.0.
% Generated on: 27-Oct-2020 22:05:21

%% Antenna Properties 
% Define antenna 
antennaObject = biquad;
% Properties changed 
antennaObject.ArmLength = 0.305;

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 2800000000;
% Define frequency range 
freqRange = (2520:28:3080) * 1e6;
% show for biquad
figure;
show(antennaObject) 
figure;
pattern(antennaObject,plotFrequency)


